### ISSUE TITLE
pattern for `@type`

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#48]
@olinux how do we define the pattern for `@type` in SANDS (v0.1) and openMINDS (v3.0)?

Options:  
1. `"@type": "https://schema.hbp/sands/SchemaName"`
2. `"@type": "https://schema.hbp/SchemaName"`
3. `"@type": "https://schema.ebrains/sands/SchemaName"`
4. `"@type": "https://schema.ebrains/SchemaName"`

Or something even different?

**Comment by apdavison** [comment]
Slightly tangential to the topic, but:

If openMINDS and SANDS are supposed to be open standards, then I think they should have their own domains, e.g.

"https://openminds.net/schema/" or "https://openminds.eu/schema/", plus "http://sands.eu/schema", etc.

At the least we should have an openminds domain - SANDS could be considered a subsidiary schema, since I guess it needs to be used in conjunction with openMINDS. 

The same domain could be used for Tier 3 schemas - I was thinking that these could be presented as openMINDS extensions, e.g. "openMINDS/electrophysiology", "openMINDS/analysis", etc.

**Comment by lzehl** [comment]
@apdavison  : this is a good point and highly related to what I wrote in #49. 
I think having openMINDS as its own domain with all extensions (tier 2 and tier 3) would be nice.   
Do you think that the corresponding schemas should also be merged into one GitHub Repo then?

**Comment by apdavison** [comment]
> Do you think that the corresponding schemas should also be merged into one GitHub Repo then?

No, I think it's ok to keep them in separate repos.

**Comment by lzehl** [comment]
okay. that makes it unnecessary to think about restructuring the repos :+1:

**Comment by olinux** [comment]
https://schema.ebrains.eu/openminds
https://sands.schema.ebrains.eu
https://neuralactivity.schema.ebrains.eu

https://core.openminds.*/dataset

**Comment by lzehl** [comment]
`@type: https://openminds.ebrains.eu/sands/schemaName`

**Comment by lzehl** [comment]
please also change `$id == @type`

**Comment by UlrikeS91** [comment]
solved differently and can be closed
