### ISSUE TITLE
use-case discussion: semantic anchoring

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#57]
@aeidi89 , @UlrikeS91 , @blixilla , @skoehnen I started to think about how the current model is used for pure semantic anchoring and like to here your opinion on this topic before requesting any (possibly necessary) changes / extensions to the SANDS model.

Let's assume the receptor datasets as example:

Situation in the data:
  - delivered data files contain averaged receptor density measurements for a selected brain region (no image file)
  - the brain region was identified using the same method as used for the Julich-Brain Atlas
  - we do not get any proof of the corresponding annotations made for brain region used in the receptor data
  - some of the brain regions in the receptor data are not yet covered in the Julich-Brain Atlas

Two questions arise from this scenario:
1) how do we handle user-defined naming of brain regions that are inspired by an atlas terminology?
2) how do we capture pure semantic relation between the content of a non-image file and an anatomical entity?

To some extent these handling of the two question is connected. Here, how it could be handled in the current models:
- a) studyTarget that links to the anatomicalEntity of the Julich-Brain Atlas brain region is defined in openMINDS and attached to the protocolExecution that produces the non-image file(s) containing the corresponding receptor density measurements
- b) annotation is generated in SANDS that 
    - links to a user-defined anatomicalEntity for namingTerm, and the corresponding anatomicalEntity of the Julich-Brain region for the relatedAtlasTerm (considering the receptor density, this can or cannot be the same anatomicalEntity)
    - does not have an inspiredBy
    - does not have a visualizedIn (here is a conflict: we do require this now to be present) 

Doing a) and b) does seem a bit much especially because we do not really get any files for the annotation in such cases.   
Would we consider only a) sufficient for capturing pure semantic anchoring?

**Comment by UlrikeS91** [comment]
> 1. how do we handle user-defined naming of brain regions that are inspired by an atlas terminology?

I think that this can be covered by SANDS (as it is now) already:
`anatomicalEntity` only has one required field (`nameOfLocation`) and by leaving out the `relatedOntology` it indirectly says that this is user-defined. In addition, to reflect that it has been inspired by an atlas terminology, the user-defined `anatomicalEntity` can be related to the atlas term that inspired it via `entityToEntity` (subject being atlas term, object being user-defined term). `entityToEntity` would be able to cover that the `relationType` is e.g. identical, but with e.g. a low `confidence` (since 2D section images are missing and it cannot be confirmed).    

> 2. how do we capture pure semantic relation between the content of a non-image file and an anatomical entity?

This one is less straight-forward to me. There are a few cases that should be considered: Does the non-image file contain data originating from image file(s)? 
Answer "No": This could e.g. be an e-phys recording and one can link this file to an `electrodeContact` which is indirectly linked to a `coordinateSpace`. The `coordinatePoint` would give the relation to the location in the brain. This would be highly indirectly linked to a brain region/anatomical entity and only if optional fields are filled in...

Answer "Yes": Would give a good reason to use `annotation` directly, which I don't think is possible for the other case. Then what you described comes in: 
> * b) annotation is generated in SANDS that
>   
>   * links to a user-defined anatomicalEntity for namingTerm, and the corresponding anatomicalEntity of the Julich-Brain region for the relatedAtlasTerm (considering the receptor density, this can or cannot be the same anatomicalEntity)

This sounds reasonable. If we use `entityToEntity` as described above (even though this was probably not the original intention for it...), `relatedAtlasTerm` could even be left out. 

>   * does not have an inspiredBy

Also reasonable.

>   * does not have a visualizedIn (here is a conflict: we do require this now to be present)

Yes and no. The way `visualisedIn` is intended at the moment wouldn't suit it, no. But wouldn't it be nice to specific a coordinate that can be used to anchor the annotation in space? Then the non-image file could be linked to this point and (for later purposes) e.g. visualised as a pop-up window with the file content at this coordinate point. 

> Doing a) and b) does seem a bit much especially because we do not really get any files for the annotation in such cases.
> Would we consider only a) sufficient for capturing pure semantic anchoring?

I'm not sure. a) makes sense in this case, but semantic anchoring can be more than just that, can't it? You're basing this on the assumption that the brain region is the study target, but are there cases where this is not true or gives the wrong impression? For example, my study target is a specific neuron type. This type happens to be in many brain regions, but I only looked at 2 of them. I guess one could specify this by saying "neuron type in region 1 and 2"-kind of way. But if the researcher doesn't want this because they claim it applies to it all, I'm not sure we can just force them. Then the study target would include more brain regions, but the semantic anchoring would need to specify that only those 2 were actually looked at. Do you know what I mean?

**Comment by lzehl** [comment]
@UlrikeS91 reduce in annotation criteria to be linked to protocolExecution only
@lzehl adopt protocolExecution output to also hold anatomicalEntity

**Comment by lzehl** [comment]
Discussion outcome: @lzehl add field `semanticallyAnchoredTo` to `protocolEcecution.schema.json`

**Comment by UlrikeS91** [comment]
The portion assigned to me for SAND has been implemented. See https://github.com/HumanBrainProject/openMINDS_core/issues/124 for updates on `protocolExecution.schema(.tpl).json`. 

@lzehl: The SANDS portion related to this is done. Should we close the issue?

**Comment by lzehl** [comment]
Yes. This can be closed. Thanks for the reminder.
